### ISSUE TITLE
Unable to install latest version

### ISSUE THREAD

**Issue by 8bitbuddhist** [solarwinds/docker-plugin-papertrail#3]
When installing the latest version using `docker plugin install`, I get the following error:

`Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"/usr/bin/docker-papertrail-log-driver\": stat /usr/bin/docker-papertrail-log-driver: no such file or directory": unknown`

I am able to install version `e6c7852`. Looking at the [plugin history](https://hub.docker.com/r/solarwinds/papertrail-plugin/tags/), there's a significant size difference between this version and the most recent version.

**Comment by girishranganathan** [comment]
Hello @8bitbuddhist, sorry there was a build issue which was missed. I have tried to fix it now. Can you please give it a shot?

Ty,
G

**Comment by 8bitbuddhist** [comment]
@girishranganathan Works great now, thanks!
